require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'TagTalk' do
  config = use_native_modules!
  
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
  use_react_native!(:path => config["reactNativePath"])


  target 'TagTalkTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TagTalk-tvOS' do
  # Pods for TagTalk-tvOS

  target 'TagTalk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
